### ISSUE TITLE
Keeps returning 404 in production (next build) Nextjs 14.2.4 app router

### ISSUE THREAD

**Issue by tomferez** [muxinc/blurup#2]
Everything runs just fine in dev mode, but after built and running it in prod returns 404 on every fetch.

`Error: [@mux/blurhash] Error fetching thumbnail. 404: Not Found
    at E (/Users/ecolekoenig/GitFolders/prismic-test-effe/.next/server/chunks/187.js:2981:15979)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async a (/Users/ecolekoenig/GitFolders/prismic-test-effe/.next/server/chunks/527.js:7:7654)
    at async p (/Users/ecolekoenig/GitFolders/prismic-test-effe/.next/server/chunks/527.js:7:6305) {
  digest: '207954898'
}`

**Comment by tomferez** [comment]
Seems it was an issue with Next cache... Deleted .next folder, rebuilt the project and it worked like magic.

**Comment by daytime-em** [comment]
Happy to hear you were able to resolve your issue. Let us know if you see any more issues!
